repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: uv-lock
        name: uv lock
        language: system
        entry: uv
        args: [lock, --check]
        files: .*(uv\.lock|pyproject\.toml|uv\.toml)$
        pass_filenames: false
      - id: uv-sync
        name: uv sync
        language: system
        entry: uv
        args: [sync, --frozen, --all-groups, --all-extras, --all-packages]
        always_run: true
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        language: system
        entry: uv
        args: [run, --no-sync, ruff, check, --fix]
        types: [file, python]
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv
        args: [run, --no-sync, ruff, format]
        types: [file, python]
      - id: mypy
        name: mypy
        language: system
        entry: uv
        args: [run, --no-sync, mypy]
        types: [file, python]
